name: Godot toolkit install
author: Pawel Lampe
description: Install the Godot toolkit
branding:
  icon: activity
  color: blue

inputs:
  version:
    description: Version of the gdtoolkit to install
    default: "4.*"

runs:
  using: composite
  steps:
    - id: create-requirements-if-not-exists
      run: |
        if [ ! -f requirements.txt ]; then
          echo "gdtoolkit==${{inputs.version}}" > requirements.txt
        fi
      shell: bash

    - id: install-python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: "pip"

    - id: setup-build-tools
      run: pip install build
      shell: bash

    - name: checkout
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
        repository: tibtiq/godot-gdscript-toolkit
        path: godot-gdscript-toolkit

    - id: build-library
      run: python -m build godot-gdscript-toolkit
      shell: bash

    - name: install-library
      run: pip install godot-gdscript-toolkit/dist/gdtoolkit-4.2.3-py3-none-any.whl
      shell: bash

    - name: clean-up
      run: rm -rf godot-gdscript-toolkit
      shell: bash
